name: Crear repositorio y agregar colaboradores

on:
  issues:
    types: [opened, edited]
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'

jobs:
  crear-repositorio:
    runs-on: ubuntu-latest

    steps:
    - name: Crear repositorio y agregar colaboradores
      id: add-collaborators
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GIT_DATA }}
        script: |
          const orgName = 'Try-Catch-Factory'
          const issueTitle = `${context.payload.issue.title}`
          const issueBody = `${context.payload.issue.body}`

          if (!issueTitle) {
            console.log('El título de la issue no puede estar vacío.')
            return
          }

          const repoName = issueTitle

          // Crear el nuevo repositorio
          await github.rest.repos.createInOrg({
            org: orgName,
            name: repoName,
            description: issueBody
          })

          const collaborators = issueBody.split(',').map(name => name.trim())

          for (const collaborator of collaborators) {
            try {
              const user = await github.rest.users.getByUsername({ username: collaborator })
              await github.rest.repos.addCollaborator({
                owner: orgName,
                repo: repoName,
                username: collaborator
              })
              console.log(`Usuario ${collaborator} agregado como colaborador del repositorio ${repoName}`)
            } catch (error) {
              console.log(`Error al agregar el usuario ${collaborator}: ${error.message}`)
            }
          }

          if (context.eventName === 'issues') {
            const originalRepoName = context.payload.issue.repo.name
            await github.rest.issues.update({
              owner: orgName,
              repo: originalRepoName,
              issue_number: context.payload.issue.number,
              state: 'closed'
            })
            console.log(`Issue #${context.payload.issue.number} cerrada en el repositorio ${originalRepoName}.`)
          }
